services:
  - type: web
    name: cms-school-demo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: RUN_MIGRATIONS
        value: "true"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-free-mysql-host.aivencloud.com
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
